export const OBTENER_PAISES = 'OBTENER_PAISES';
export const AGREGAR_PAIS = 'AGREGAR_PAIS';
export const VALIDAR_FORMULARIO='VALIDAR_FORMULARIO';
export const SELECCIONAR_PAIS='SELECCIONAR_PAIS';
export const ELIMINAR_PAIS='ELIMINAR_PAIS';
export const EDITAR_PAIS='EDITAR_PAIS'
export const OBTENER_PAIS = 'OBTENER_PAIS';

export const OBTENER_CIUDADES = 'OBTENER_CIUDADES';
export const AGREGAR_CIUDAD = 'AGREGAR_CIUDAD';
export const SELECCIONAR_CIUDAD='SELECCIONAR_CIUDAD';
export const ELIMINAR_CIUDAD='ELIMINAR_CIUDAD';
export const EDITAR_CIUDAD='EDITAR_CIUDAD';
export const OBTENER_CIUDAD = 'OBTENER_CIUDAD';

export const OBTENER_EMPRESAS = 'OBTENER_EMPRESAS';
export const AGREGAR_EMPRESA = 'AGREGAR_EMPRESA';
export const SELECCIONAR_EMPRESA='SELECCIONAR_EMPRESA';
export const ELIMINAR_EMPRESA='ELIMINAR_EMPRESA';
export const EDITAR_EMPRESA='EDITAR_EMPRESA'

export const AGREGAR_PUESTO='AGREGAR_PUESTO';
export const OBTENER_PUESTOS='OBTENER_PUESTOS'
export const SELECCIONAR_PUESTO='SELECCIONAR_PUESTO';
export const EDITAR_PUESTO='EDITAR_PUESTO';
export const ELIMINAR_PUESTO='ELIMINAR_PUESTO';